version: '3.8'

services:
  api:
    build: .
    container_name: gestao-escolar-api
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual no diretório /app do contêiner
      # Permite live-reloading durante o desenvolvimento
      - .:/app
